In [81]:
import pandas as pd

In [82]:
#importing our csv file
df = pd.read_csv("D:\Projects\E2E PROJECT 2 - RETAIL_COMPANY\DATASET\customer_shopping_behavior.csv")

In [83]:
#check tops rows of the tbale and see if the table is loading 
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53.0,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64.0,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73.0,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90.0,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49.0,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [84]:
#gives info about columns and rows
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   float64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(2), int64(3), object(13)
memory usage: 548.6+ KB

In [85]:
#gives statistical data for only numerical columns
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [86]:
#gives statistical data for all columns
df.describe(include = "all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [87]:
#optimising column names for easier uses
df.columns = df.columns.str.lower()
df.columns =  df.columns.str.replace(" ","_")
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [88]:
#renaming a column to make it easier to read
df = df.rename( columns = {"purchase_amount_(usd)" : "purchase_amount"})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [89]:
#checking for null values
df.isnull().sum()

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount            0
location                   0
size                       0
color                      0
season                     0
review_rating             37
subscription_status        0
shipping_type              0
discount_applied           0
promo_code_used            0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
dtype: int64

In [90]:
#using median() to fill up null values 
df["review_rating"] = df.groupby("category")["review_rating"].transform(lambda x : x.fillna( x.median()))
df["review_rating"]

0       3.1
1       3.1
2       3.1
3       3.5
4       2.7
       ...
3895    4.2
3896    4.5
3897    2.9
3898    3.8
3899    3.1
Name: review_rating, Length: 3900, dtype: float64

In [91]:
#checking if any null value is left after using the median()
df.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount           0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
promo_code_used           0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
dtype: int64

In [92]:
#creating labels for the new column - "age_groups" that we are creating by grouping the age numbers in the column - "ages".
labels = ["young_adult" , "adult" , "middle_age" , "senior"]
#creating the new column - "age_groups" which separates the already existing column - "ages"
df["age_groups"] = pd.qcut(df["age"],q=4, labels=labels)
#checking the separation 
df[["age_groups", "age"]]. head(10)

    age_groups  age
0   middle_age   55
1  young_adult   19
2   middle_age   50
3  young_adult   21
4   middle_age   45
5   middle_age   46
6       senior   63
7  young_adult   27
8  young_adult   26
9   middle_age   57

In [93]:
#checking the values in the column 
df["frequency_of_purchases"].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [94]:
#after checking we use map() to link a numerical value to the text values
df["days_between_puchases"] = df["frequency_of_purchases"]. map({
    "Fortnightly": 14, 
    "Weekly": 7, 
    'Annually': 365, 
    'Quarterly':90, 
    'Bi-Weekly': 14,
    'Monthly': 30,
    'Every 3 Months': 90
})

#checking if the numerical values were correctly linked to the text value
df[["days_between_puchases" , "frequency_of_purchases"]].head(10)

   days_between_puchases frequency_of_purchases
0                     14            Fortnightly
1                     14            Fortnightly
2                      7                 Weekly
3                      7                 Weekly
4                    365               Annually
5                      7                 Weekly
6                     90              Quarterly
7                      7                 Weekly
8                    365               Annually
9                     90              Quarterly

In [95]:
pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in d:\annaconda_python_jupyter\lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in d:\annaconda_python_jupyter\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in d:\annaconda_python_jupyter\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\annaconda_python_jupyter\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [96]:
# Install necessary packages if you haven't
from sqlalchemy import create_engine

# SQL Server connection (Windows Authentication)
server = "DESKTOP-0UB9GDT"
database = "RETAIL_COMPANY"

# Create SQLAlchemy engine
engine = create_engine(
    f"mssql+pyodbc://@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server"
)

# --- WRITE DataFrame to SQL ---
table_name = "retail_customer_purchases"  # your table name
df.to_sql(
    table_name,
    engine,
    if_exists="replace",  # use "append" if you want to keep existing rows
    index=False
)

# --- READ data back from SQL ---
df_sql = pd.read_sql(f"SELECT * FROM {table_name}", engine)

# Preview
df_sql.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_groups,days_between_puchases
0,1,55,Male,Blouse,Clothing,53.0,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,middle_age,14
1,2,19,Male,Sweater,Clothing,64.0,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,young_adult,14
2,3,50,Male,Jeans,Clothing,73.0,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,middle_age,7
3,4,21,Male,Sandals,Footwear,90.0,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,young_adult,7
4,5,45,Male,Blouse,Clothing,49.0,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,middle_age,365